name: Test

on: [push, pull_request]

jobs:
    lint:
        name: PlenaryBustedDirectory
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                path: refactoring.nvim
            - uses: actions/checkout@v2
              with:
                repository: neovim/nvim-lspconfig
                path: nvim-lspconfig
            - uses: actions/checkout@v2
              with:
                repository: nvim-treesitter/nvim-treesitter
                path: nvim-treesitter
            - uses: actions/checkout@v2
              with:
                repository: nvim-lua/plenary.nvim
                path: plenary.nvim
            - name: help
              run: |
                pwd
            - name: help
              run: |
                ls refactoring.nvim/lua/refactoring/tests
            - name: Setup
              run: |
                  sudo apt-get update
                  sudo add-apt-repository ppa:neovim-ppa/unstable
                  sudo apt-get install neovim
                  sudo apt install nodejs npm
                  npm install -g typescript typescript-language-server
            - name: treesitter
              run: |
                nvim --headless -c "TSInstallSync all" -c "q"
            - name: Test
              run: |
                cd refactoring.nvim
                make test

